// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjAgoUez4W5Rjy96Tiuy_kHIRXcQzXTNg',
    appId: '1:431463946737:web:13cd0f3ee997d9a5d00c50',
    messagingSenderId: '431463946737',
    projectId: 'project-01-ab6ab',
    authDomain: 'project-01-ab6ab.firebaseapp.com',
    storageBucket: 'project-01-ab6ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlLoqa6ysFSbkPYL7F7qK0WDeFBdvNnwg',
    appId: '1:431463946737:android:aaca189b26a700ddd00c50',
    messagingSenderId: '431463946737',
    projectId: 'project-01-ab6ab',
    storageBucket: 'project-01-ab6ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQq2wYLh4gJf2gG6RQ15YsNL93r2lbvMU',
    appId: '1:431463946737:ios:87dbf9a9ce8ca099d00c50',
    messagingSenderId: '431463946737',
    projectId: 'project-01-ab6ab',
    storageBucket: 'project-01-ab6ab.appspot.com',
    iosBundleId: 'com.example.project01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQq2wYLh4gJf2gG6RQ15YsNL93r2lbvMU',
    appId: '1:431463946737:ios:15bfbaabf55fd0b5d00c50',
    messagingSenderId: '431463946737',
    projectId: 'project-01-ab6ab',
    storageBucket: 'project-01-ab6ab.appspot.com',
    iosBundleId: 'com.example.project01.RunnerTests',
  );
}
